title: 'Trump Bot'
default_lang: en
author:
  name: 'Dylan Parton'
  email: djrparton@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Just a gag'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  /recruitsgdrive: 'https://drive.google.com/drive/u/0/folders/1EXp1a4sI47rgiVC3mnnoFZmvR53qs7SG'
  /recruitsterm1: 'https://www.notion.so/prtn/30591d7a36834658900354425f0e4943?v=7ac60e999ad04f2aa0def05e55c80f37'
  /recruitsterm2: 'https://www.notion.so/prtn/494b953cc2eb4f38a70f14d3a60fe29d?v=b817a1695313440d818569fe28f55c63'
routes: null
blog:
  route: /blog
